### ISSUE TITLE
Maybe you should switch to Vulkan

### ISSUE THREAD

**Issue by dkrikun** [MicBosi/VisualizationLibrary#121]
:confused:

**Comment by MicBosi** [comment]
This is a though I had as well, especially since NVidia already released the Vulkan drivers. I thought about the possibility of making a next version of VL GL-agnostic and allow the user to switch drivers, however the biggest obstacle I see at the moment (besides a complete rewrite of VL) is the lack of CUDA and OpenCL interoperability and the fact that Intel and AMD seem to be lagging quite behind.
OpenGL on the other hand is stable and mature, is not going away any time soon and it supports so many features most of us will never even use. I think instead of switching to Vulkan it'd be more useful to redesign/improve VL making it much more useful than it is now.
