### ISSUE TITLE
Coloring faces

### ISSUE THREAD

**Issue by Anastasiia-Iusupova-hub** [MicBosi/VisualizationLibrary#195]
Hi there!

Is there any option to color face? As far as I understand, it's possible to use "setColorArray" for primitive, however I don't understand the workflow for that task. Could you please provide some example?

**Comment by MicBosi** [comment]
@Anastasiia-Iusupova-hub VL follows OpenGL usual practices. In order to color a face you need to specify the color for each vertex using the color array. Depending on the topology of your geometry and type of primitive some vertices might be shared with more than one polygon. In that case if you want for such polygons to have separate colors they'll need to have separate vertices, which means you might need to duplicate some of them.
